# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fatura.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog3(object):
    def setupUi(self, Dialog3):
        Dialog3.setObjectName("Dialog3")
        Dialog3.resize(890, 625)
        self.lineEdit = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit.setGeometry(QtCore.QRect(90, 10, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 10, 151, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 70, 561, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(Dialog3)
        self.label.setGeometry(QtCore.QRect(30, 10, 46, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog3)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 46, 13))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(Dialog3)
        self.dateEdit.setGeometry(QtCore.QRect(370, 10, 110, 22))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.tableWidget = QtWidgets.QTableWidget(Dialog3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 641, 131))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 240, 641, 351))
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(90)
        self.pushButton = QtWidgets.QPushButton(Dialog3)
        self.pushButton.setGeometry(QtCore.QRect(670, 430, 111, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/nenra.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog3)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 490, 111, 51))
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Dialog3)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 491, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog3)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog3)
        self.label_5.setGeometry(QtCore.QRect(730, 70, 41, 31))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog3)
        self.label_6.setGeometry(QtCore.QRect(420, 600, 181, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog3)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 340, 111, 31))
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog3)
        self.pushButton_4.setGeometry(QtCore.QRect(780, 10, 91, 41))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.dateEdit_2 = QtWidgets.QDateEdit(Dialog3)
        self.dateEdit_2.setGeometry(QtCore.QRect(580, 10, 110, 22))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_7 = QtWidgets.QLabel(Dialog3)
        self.label_7.setGeometry(QtCore.QRect(530, 10, 31, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_4.setGeometry(QtCore.QRect(610, 40, 61, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(Dialog3)
        self.label_8.setGeometry(QtCore.QRect(570, 40, 31, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog3)
        self.lineEdit_5.setGeometry(QtCore.QRect(790, 60, 71, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog3)
        self.pushButton_5.setGeometry(QtCore.QRect(770, 90, 101, 31))
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(Dialog3)
        self.comboBox.setGeometry(QtCore.QRect(770, 150, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog3)
        self.pushButton_2.clicked.connect(Dialog3.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog3)
        Dialog3.setTabOrder(self.lineEdit, self.lineEdit_2)
        Dialog3.setTabOrder(self.lineEdit_2, self.dateEdit)
        Dialog3.setTabOrder(self.dateEdit, self.lineEdit_4)
        Dialog3.setTabOrder(self.lineEdit_4, self.lineEdit_3)
        Dialog3.setTabOrder(self.lineEdit_3, self.tableWidget)
        Dialog3.setTabOrder(self.tableWidget, self.tableWidget_2)
        Dialog3.setTabOrder(self.tableWidget_2, self.pushButton)
        Dialog3.setTabOrder(self.pushButton, self.pushButton_2)
        Dialog3.setTabOrder(self.pushButton_2, self.lineEdit_5)
        Dialog3.setTabOrder(self.lineEdit_5, self.pushButton_5)
        Dialog3.setTabOrder(self.pushButton_5, self.pushButton_3)
        Dialog3.setTabOrder(self.pushButton_3, self.pushButton_4)
        Dialog3.setTabOrder(self.pushButton_4, self.dateEdit_2)

    def retranslateUi(self, Dialog3):
        _translate = QtCore.QCoreApplication.translate
        Dialog3.setWindowTitle(_translate("Dialog3", "Fiş Girişi"))
        self.label.setText(_translate("Dialog3", "Seri/Sıra"))
        self.label_2.setText(_translate("Dialog3", "Cari "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog3", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog3", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog3", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog3", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog3", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog3", "Ürün Kodu"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog3", "Ürün Açıklama"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog3", "Birim"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog3", "KDV"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog3", "Miktar"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Dialog3", "Birim Fiyat"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Dialog3", "Toplam"))
        self.pushButton.setText(_translate("Dialog3", "Kaydet"))
        self.pushButton_2.setText(_translate("Dialog3", "İptal"))
        self.label_4.setText(_translate("Dialog3", "Ara"))
        self.label_6.setText(_translate("Dialog3", "TextLabel"))
        self.pushButton_3.setText(_translate("Dialog3", "Satır Sil"))
        self.pushButton_4.setText(_translate("Dialog3", "Fiş Sil"))
        self.label_7.setText(_translate("Dialog3", "Vade"))
        self.label_8.setText(_translate("Dialog3", "Gün"))
        self.pushButton_5.setText(_translate("Dialog3", "Fiş Getir"))
        self.comboBox.setItemText(0, _translate("Dialog3", "ÖDEME YAP"))
        self.comboBox.setItemText(1, _translate("Dialog3", "Nakit Ödeme"))
        self.comboBox.setItemText(2, _translate("Dialog3", "Denizbank "))
        self.comboBox.setItemText(3, _translate("Dialog3", "Yapı Kredi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog3 = QtWidgets.QDialog()
    ui = Ui_Dialog3()
    ui.setupUi(Dialog3)
    Dialog3.show()
    sys.exit(app.exec_())

